---
title: "Replication of Study 3 by Brown-Iannuzzi et al. (2016, Psychological Science)"
author: "Maggie Perry (mperry3@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

##Introduction

###Justification for Choice of Experiment:
This study provides evidence of a correlation between racially biased mental images of welfare recipients and support for welfare distribution. This is an important finding in the context of understanding how racial bias impacts institutional decisions, which I plan to explore throughout my research program. Through this replication, I will gain more understanding of how implicit associations about race can affect one's attitudes toward various laws and policies. 

###Description of Paper:
In the first two studies in the paper (Brown-Iannuzzi, Dotsch, Cooley, & Payne, 2016), participants selected welfare recipients and non-welfare recipients from a series of face images, and their selections were combined to create an average welfare-recipient and average non-welfare-recipient face. A separate sample rated the average welfare-recipient as appearing significantly more African-American than the non-welfare-recipient. I plan to replicate Study 3, in which participants were significantly less likely to award welfare benefits to the average welfare-recipient (more African-American appearing) image. 

###Description of the stimuli and procedures that will be required to conduct this experiment:
Participants will be recruited on Amazon Mechanical Turk (exact sample size to be determined by power analysis) to complete the study via Qualtrics. Face images used in Study 3 (2 representative images and 4 filler images) will be collected from the original authors for use. 

Measures for each face image will include:
-Perceived race
-Perceived competence
-Perceived degree of hardworking
-Perceived responsibility
-Perceived ability to use food stamps/cash assistance responsibly
-Supoort for giving person food stamps/cash assistance

General measures will include:
-Demographics (age, gender, race)
-Attitudes toward welfare
-Perceptions of increasing diversity in America
-Perceptions of welfare as being for racial minorities

###Anticipated challenges
Potential challenges could include acquiring the images from the original authors, and finding alternative images if unable to get the original images. 


##Methods

###Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

###Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

###Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

###Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
